### PR TITLE
Issue #111: "Save downloaded media with post date as modification timestamp"

### LINKED ISSUE #111: Save downloaded media with post date as modification timestamp
**Expected Behaviour**

When crawling a blog that contains posts with inlined media (e.g. html in the post), the image and video files should have the modification timestamp of the original post date too.

**Actual Behaviour**

The images and videos are saved with the current date and time.

**Steps to Reproduce the Problem**

  1. Download a blog with several blog entries over a period of time
  2. After the download has finished, check the file timestamps.

**Specifications**

current TumblThree version

### PR DESCRIPTION
**Pull request by arrowsmith001**
## Title

Issue #111: "Save downloaded media with post date as modification timestamp"

## Description

When inlined (HTML-embedded) media is downloaded from a post, it's timestamp is set to the current date and time. The preferred outcome is that it's timestamp is the same as the post's timestamp.

## Issue Resolution

This Pull Request Fixes #111 Save downloaded media with post date as modification timestamp

## Proposed Changes

In AbstractTumblrCrawler I have made some changes to a few methods (AddPhotoUrl, AddVideoUrl, etc) - which are called by TumblrBlogCrawler methods named "AddInline..." or "AddGenericInline..." - by including a parameter "postTimestamp" to pass through to the "PhotoPost" or "VideoPost" constructor. This parameter is nullable since there are cases where an entire document string is passed through and no post timestamp can be associated with it.

## New or Changed Features

Embedded media is timestamped according to the post where it originates.

### CODE REVIEW

File: src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs [hunk 1]
```diff
@@ -440,6 +440,7 @@ private async Task AddUrlsToDownloadListAsync(TumblrApiJson document)
                 if (!PostWithinTimeSpan(post)) { continue; }
                 if (!CheckIfContainsTaggedPost(post)) { continue; }
                 if (!CheckIfDownloadRebloggedPosts(post)) { continue; }
+                string postTimestamp = post.Date;
```
Comment (thomas694) [inline src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs:443]: Why is this line needed?

**Review by thomas694 — COMMENTED** [review]
In total it looks well.

File: src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs (hunk 1 above)
Comment (arrowsmith001) [reply src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs]: It is not. I forgot to remove it. It has been deleted now.

**Review by thomas694 — APPROVED** [review]
